services:
  - type: web
    name: junkshop-pos-website
    env: docker
    plan: starter
    rootDir: web-admin
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: junkshop-pos-website
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /tmp/database.sqlite

