import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateReceiptPDF = async (transaction, items, shopSettings) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const shopName = shopSettings.shop_name || 'JUNKSHOP POS SYSTEM';
    const dateStr = new Date(transaction.created_at + ' UTC').toLocaleString();
    const transNo = transaction.transaction_number;

    // --- Header ---
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(shopName.toUpperCase(), 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('OFFICIAL RECEIPT', 105, 28, { align: 'center' });

    // --- Transaction Info ---
    doc.setDrawColor(200, 200, 200);
    doc.line(15, 35, 195, 35);

    doc.setFontSize(10);
    doc.text(`Date: ${dateStr}`, 15, 45);
    doc.text(`Transaction #: ${transNo}`, 15, 50);
    doc.text(`Cashier: ${transaction.cashier_name || 'System'}`, 15, 55);

    if (transaction.customer_name) {
        doc.setFont('helvetica', 'bold');
        doc.text(`Customer: ${transaction.customer_name}`, 195, 45, { align: 'right' });
        doc.setFont('helvetica', 'normal');
    } else {
        doc.text(`Customer: Walk-in`, 195, 45, { align: 'right' });
    }

    // --- Items Table ---
    const tableData = items.map(item => [
        item.product_name || item.name,
        `${item.weight_kg || item.weight} kg`,
        `PHP ${(item.subtotal / (item.weight_kg || item.weight)).toFixed(2)}`,
        `PHP ${item.subtotal.toFixed(2)}`
    ]);

    autoTable(doc, {
        startY: 65,
        head: [['Item Description', 'Weight', 'Price/kg', 'Subtotal']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [14, 165, 233], textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 5 },
        columnStyles: {
            0: { cellWidth: 'auto' },
            1: { cellWidth: 30, halign: 'center' },
            2: { cellWidth: 40, halign: 'right' },
            3: { cellWidth: 40, halign: 'right' }
        }
    });

    // --- Summary ---
    const finalY = doc.lastAutoTable.finalY + 10;
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL AMOUNT:', 140, finalY, { align: 'right' });
    doc.text(`PHP ${transaction.total_amount.toFixed(2)}`, 195, finalY, { align: 'right' });

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Payment Received:', 140, finalY + 7, { align: 'right' });
    doc.text(`PHP ${transaction.payment_received.toFixed(2)}`, 195, finalY + 7, { align: 'right' });

    doc.text('Change:', 140, finalY + 12, { align: 'right' });
    doc.text(`PHP ${transaction.change_amount.toFixed(2)}`, 195, finalY + 12, { align: 'right' });

    // --- Footer ---
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('Thank you for your business!', 105, 280, { align: 'center' });
    doc.text('Generated by Junkshop POS System', 105, 285, { align: 'center' });

    // Convert to base64 and return
    const pdfBase64 = doc.output('datauristring').split(',')[1];
    return {
        filename: `Receipt-${transNo}.pdf`,
        base64Data: pdfBase64
    };
};
