import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateReceiptPDF = async (transaction, items, shopSettings) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const shopName = shopSettings.shop_name || 'JUNKSHOP POS SYSTEM';
    const dateStr = new Date(transaction.created_at + ' UTC').toLocaleString();
    const transNo = transaction.transaction_number;

    // --- Header ---
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(shopName.toUpperCase(), 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('OFFICIAL RECEIPT', 105, 28, { align: 'center' });

    // --- Transaction Info ---
    doc.setDrawColor(200, 200, 200);
    doc.line(15, 35, 195, 35);

    doc.setFontSize(10);
    doc.text(`Date: ${dateStr}`, 15, 45);
    doc.text(`Transaction #: ${transNo}`, 15, 50);
    doc.text(`Cashier: ${transaction.cashier_name || 'System'}`, 15, 55);

    if (transaction.customer_name) {
        doc.setFont('helvetica', 'bold');
        doc.text(`Customer: ${transaction.customer_name}`, 195, 45, { align: 'right' });
        doc.setFont('helvetica', 'normal');
    } else {
        doc.text(`Customer: Walk-in`, 195, 45, { align: 'right' });
    }

    // --- Items Table ---
    const tableData = items.map(item => [
        item.product_name || item.name,
        `${item.weight_kg || item.weight} kg`,
        `PHP ${(item.subtotal / (item.weight_kg || item.weight)).toFixed(2)}`,
        `PHP ${item.subtotal.toFixed(2)}`
    ]);

    autoTable(doc, {
        startY: 65,
        head: [['Item Description', 'Weight', 'Price/kg', 'Subtotal']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [14, 165, 233], textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 5 },
        columnStyles: {
            0: { cellWidth: 'auto' },
            1: { cellWidth: 30, halign: 'center' },
            2: { cellWidth: 40, halign: 'right' },
            3: { cellWidth: 40, halign: 'right' }
        }
    });

    // --- Summary ---
    const finalY = doc.lastAutoTable.finalY + 10;
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL AMOUNT:', 140, finalY, { align: 'right' });
    doc.text(`PHP ${transaction.total_amount.toFixed(2)}`, 195, finalY, { align: 'right' });

    // Only show Payment and Change for cash sales (completed)
    if (transaction.status === 'completed') {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text('Payment Received:', 140, finalY + 7, { align: 'right' });
        doc.text(`PHP ${transaction.payment_received.toFixed(2)}`, 195, finalY + 7, { align: 'right' });

        doc.text('Change:', 140, finalY + 12, { align: 'right' });
        doc.text(`PHP ${transaction.change_amount.toFixed(2)}`, 195, finalY + 12, { align: 'right' });
    } else {
        // Show remaining balance for partial/unpaid
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(225, 29, 72); // rose-600
        const remaining = transaction.total_amount - (transaction.paid_amount || 0);
        doc.text('REMAINING BALANCE:', 140, finalY + 7, { align: 'right' });
        doc.text(`PHP ${remaining.toFixed(2)}`, 195, finalY + 7, { align: 'right' });
        doc.setTextColor(0, 0, 0);
    }

    // --- Footer ---
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('Thank you for your business!', 105, 280, { align: 'center' });
    doc.text('Generated by Junkshop POS System', 105, 285, { align: 'center' });

    // Convert to base64 and return
    const pdfBase64 = doc.output('datauristring').split(',')[1];
    return {
        filename: `Receipt-${transNo}.pdf`,
        base64Data: pdfBase64
    };
};

export const generateReportPDF = async (reportData, shopSettings, period) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const shopName = shopSettings.shop_name || 'JUNKSHOP POS SYSTEM';
    const shopLogo = shopSettings.shop_logo;
    const reportDate = new Date().toLocaleDateString();
    const reportTitle = `${period.toUpperCase()} REPORT`;

    // Function to add Header and Footer to each page
    const addHeaderFooter = (data) => {
        // --- Header ---
        let currentY = 15;
        if (shopLogo) {
            try {
                // Center the logo
                // Assuming logo is roughly square, 20x20mm
                doc.addImage(shopLogo, 'PNG', 105 - 10, currentY, 20, 20);
                currentY += 25;
            } catch (err) {
                console.error('Failed to add logo to PDF', err);
            }
        }

        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.text(shopName.toUpperCase(), 105, currentY, { align: 'center' });
        currentY += 10;

        doc.setFontSize(14);
        doc.text(reportTitle, 105, currentY, { align: 'center' });
        currentY += 5;
        
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(`Generated on: ${reportDate}`, 105, currentY, { align: 'center' });
        
        // Line separator
        doc.setDrawColor(200, 200, 200);
        doc.line(15, currentY + 5, 195, currentY + 5);

        // --- Footer ---
        const pageCount = doc.internal.getNumberOfPages();
        doc.setFontSize(10);
        doc.text(`Page ${data.pageNumber} of ${pageCount}`, 105, 285, { align: 'center' });
    };

    // --- Content: Summary Table ---
    const summaryHead = [['Item Name', 'Total Weight (kg)', 'Total Purchases']];
    const summaryBody = reportData.summary.map(p => [
        p.name,
        p.total_weight.toFixed(2),
        `PHP ${p.total_amount.toFixed(2)}`
    ]);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('SCRAP SALES SUMMARY', 15, shopLogo ? 65 : 45);

    autoTable(doc, {
        startY: shopLogo ? 70 : 50,
        head: summaryHead,
        body: summaryBody,
        theme: 'grid',
        headStyles: { fillColor: [14, 165, 233], textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 3 },
    });

    const totalPurchases = reportData.summary.reduce((acc, p) => acc + p.total_amount, 0);
    const totalWeight = reportData.summary.reduce((acc, p) => acc + p.total_weight, 0);

    const summaryY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`TOTAL WEIGHT: ${totalWeight.toFixed(2)} kg`, 195, summaryY, { align: 'right' });
    doc.text(`GRAND TOTAL: PHP ${totalPurchases.toLocaleString(undefined, { minimumFractionDigits: 2 })}`, 195, summaryY + 6, { align: 'right' });

    // --- Content: Transactions Table ---
    const transHead = [['ID', 'Date', 'Time', 'Customer', 'Cashier', 'Total']];
    const transBody = reportData.transactions.map(t => [
        t.transaction_number,
        new Date(t.created_at + ' UTC').toLocaleDateString(),
        new Date(t.created_at + ' UTC').toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        t.customer_name || 'Walk-in',
        t.cashier_name || 'System',
        `PHP ${t.total_amount.toFixed(2)}`
    ]);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('TRANSACTION DETAILS', 15, doc.lastAutoTable.finalY + 15);

    autoTable(doc, {
        startY: doc.lastAutoTable.finalY + 20,
        head: transHead,
        body: transBody,
        theme: 'striped',
        headStyles: { fillColor: [71, 85, 105], textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 9, cellPadding: 2 },
        didDrawPage: (data) => {
            // This will be called after each page is drawn
            // We'll use a second pass to add header/footer because we need total page count
        }
    });

    // --- Add Header and Footer to all pages ---
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        
        // Header
        let currentY = 15;
        if (shopLogo) {
            try {
                doc.addImage(shopLogo, 'PNG', 105 - 10, currentY, 20, 20);
                currentY += 25;
            } catch (err) {}
        }
        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.text(shopName.toUpperCase(), 105, currentY, { align: 'center' });
        currentY += 8;
        doc.setFontSize(12);
        doc.text(reportTitle, 105, currentY, { align: 'center' });
        currentY += 5;
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.text(`Generated on: ${reportDate}`, 105, currentY, { align: 'center' });
        doc.line(15, currentY + 3, 195, currentY + 3);

        // Footer
        doc.setFontSize(10);
        doc.text(`Page ${i} of ${totalPages}`, 105, 287, { align: 'center' });
    }

    const pdfBase64 = doc.output('datauristring').split(',')[1];
    return {
        filename: `Report_${period}_${new Date().toISOString().split('T')[0]}.pdf`,
        base64Data: pdfBase64
    };
};
