import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateReceiptPDF = async (transaction, items, shopSettings) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const shopName = shopSettings.shop_name || 'JUNKSHOP POS SYSTEM';
    const dateStr = new Date(transaction.created_at + ' UTC').toLocaleString();
    const transNo = transaction.transaction_number;

    // --- Header ---
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(shopName.toUpperCase(), 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('OFFICIAL RECEIPT', 105, 28, { align: 'center' });

    // --- Transaction Info ---
    doc.setDrawColor(200, 200, 200);
    doc.line(15, 35, 195, 35);

    doc.setFontSize(10);
    doc.text(`Date: ${dateStr}`, 15, 45);
    doc.text(`Transaction #: ${transNo}`, 15, 50);
    doc.text(`Cashier: ${transaction.cashier_name || 'System'}`, 15, 55);

    if (transaction.customer_name) {
        doc.setFont('helvetica', 'bold');
        doc.text(`Customer: ${transaction.customer_name}`, 195, 45, { align: 'right' });
        doc.setFont('helvetica', 'normal');
    } else {
        doc.text(`Customer: Walk-in`, 195, 45, { align: 'right' });
    }

    // --- Items Table ---
    const tableData = items.map(item => [
        item.product_name || item.name,
        `${item.weight_kg || item.weight} kg`,
        `PHP ${(item.subtotal / (item.weight_kg || item.weight)).toFixed(2)}`,
        `PHP ${item.subtotal.toFixed(2)}`
    ]);

    autoTable(doc, {
        startY: 65,
        head: [['Item Description', 'Weight', 'Price/kg', 'Subtotal']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [14, 165, 233], textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 5 },
        columnStyles: {
            0: { cellWidth: 'auto' },
            1: { cellWidth: 30, halign: 'center' },
            2: { cellWidth: 40, halign: 'right' },
            3: { cellWidth: 40, halign: 'right' }
        }
    });

    // --- Summary ---
    const finalY = doc.lastAutoTable.finalY + 10;
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL AMOUNT:', 140, finalY, { align: 'right' });
    doc.text(`PHP ${transaction.total_amount.toFixed(2)}`, 195, finalY, { align: 'right' });

    // Only show Payment and Change for cash sales (completed)
    if (transaction.status === 'completed') {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text('Payment Received:', 140, finalY + 7, { align: 'right' });
        doc.text(`PHP ${transaction.payment_received.toFixed(2)}`, 195, finalY + 7, { align: 'right' });

        doc.text('Change:', 140, finalY + 12, { align: 'right' });
        doc.text(`PHP ${transaction.change_amount.toFixed(2)}`, 195, finalY + 12, { align: 'right' });
    } else {
        // Show remaining balance for partial/unpaid
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(225, 29, 72); // rose-600
        const remaining = transaction.total_amount - (transaction.paid_amount || 0);
        doc.text('REMAINING BALANCE:', 140, finalY + 7, { align: 'right' });
        doc.text(`PHP ${remaining.toFixed(2)}`, 195, finalY + 7, { align: 'right' });
        doc.setTextColor(0, 0, 0);
    }

    // --- Footer ---
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('Thank you for your business!', 105, 280, { align: 'center' });
    doc.text('Generated by Junkshop POS System', 105, 285, { align: 'center' });

    // Convert to base64 and return
    const pdfBase64 = doc.output('datauristring').split(',')[1];
    return {
        filename: `Receipt-${transNo}.pdf`,
        base64Data: pdfBase64
    };
};

export const generatePriceListPDF = async (products, shopSettings) => {
    const doc = new jsPDF({
        orientation: 'landscape',
        unit: 'mm',
        format: 'a4'
    });

    const shopName = shopSettings.shop_name || 'JUNKSHOP POS SYSTEM';
    const shopLogo = shopSettings.shop_logo;

    // --- Header ---
    let currentY = 15;

    if (shopLogo) {
        try {
            // Center the logo
            doc.addImage(shopLogo, 'PNG', 148.5 - 20, currentY, 40, 40, undefined, 'FAST');
            currentY += 50; // Adjusted gap for size 18 font
        } catch (e) {
            console.error('Error adding logo to PDF', e);
        }
    }

    doc.setFontSize(18); // Junkshop name size 18
    doc.setFont('helvetica', 'normal');
    doc.text(shopName.toUpperCase(), 148.5, currentY, { align: 'center' });
    currentY += 15; // Space before table

    // --- Table ---
    const activeProducts = products.filter(p => p.status !== 'inactive');
    const tableData = activeProducts.map(p => [
        p.name.toUpperCase(),
        `P ${p.price_per_kg.toFixed(2)}`
    ]);

    autoTable(doc, {
        startY: currentY,
        head: [['WE BUY', 'PRICE']],
        body: tableData,
        theme: 'grid',
        showHead: 'firstPage', // Changed from 'first' to 'firstPage'
        headStyles: { 
            fillColor: [240, 240, 240], 
            textColor: [0, 0, 0], 
            fontStyle: 'bold', 
            fontSize: 20, // Headers bold size 20
            halign: 'center',
            lineWidth: 0.5,
            lineColor: [0, 0, 0]
        },
        styles: { 
            fontSize: 18, // Item names and price size 18
            cellPadding: 5, 
            fontStyle: 'normal',
            textColor: [0, 0, 0],
            lineWidth: 0.5,
            lineColor: [0, 0, 0]
        },
        columnStyles: {
            0: { cellWidth: 'auto', halign: 'left' },
            1: { cellWidth: 60, halign: 'center' }
        },
        margin: { left: 20, right: 20 }
    });

    const pdfBase64 = doc.output('datauristring').split(',')[1];
    return {
        filename: `PriceList-${shopName.replace(/\s+/g, '-')}.pdf`,
        base64Data: pdfBase64
    };
};

export const generateReportPDF = async (reportData, shopSettings, period, startDate, endDate) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const shopName = shopSettings.shop_name || 'JUNKSHOP POS SYSTEM';
    const shopLogo = shopSettings.shop_logo;
    const reportDate = new Date().toLocaleDateString();
    
    let reportTitle = `${period.toUpperCase()} REPORT`;
    let periodStr = "";
    if (period === 'custom' && startDate && endDate) {
        periodStr = `${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`;
    }

    // --- Content: Summary Table ---
    const summaryHead = [['Item Name', 'Total Weight (kg)', 'Total Purchases']];
    const summaryBody = reportData.summary.map(p => [
        p.name,
        p.total_weight.toFixed(2),
        `PHP ${p.total_amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
    ]);

    const totalPurchases = reportData.summary.reduce((acc, p) => acc + p.total_amount, 0);
    const totalWeight = reportData.summary.reduce((acc, p) => acc + p.total_weight, 0);

    // Add Total Row to Summary Body
    summaryBody.push([
        { content: 'TOTAL', colSpan: 1, styles: { halign: 'right', fontStyle: 'bold', fillColor: [241, 245, 249] } },
        { content: `${totalWeight.toFixed(2)} kg`, styles: { halign: 'center', fontStyle: 'bold', fillColor: [241, 245, 249] } },
        { content: `PHP ${totalPurchases.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, styles: { halign: 'right', fontStyle: 'bold', fillColor: [241, 245, 249] } }
    ]);

    // Content starts after header space
    const contentStartY = shopLogo ? 75 : 50;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('SCRAP SALES SUMMARY', 15, contentStartY);

    autoTable(doc, {
        startY: contentStartY + 5,
        head: summaryHead,
        body: summaryBody,
        theme: 'grid',
        headStyles: { fillColor: [14, 165, 233], textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 3 },
        margin: { top: contentStartY + 5, bottom: 25 },
        columnStyles: {
            0: { cellWidth: 'auto' },
            1: { cellWidth: 40, halign: 'center' },
            2: { cellWidth: 50, halign: 'right' }
        }
    });

    const summaryY = doc.lastAutoTable.finalY + 15;

    // --- Content: Transactions Table ---
    const transHead = [['ID', 'Date', 'Time', 'Customer', 'Cashier', 'Total']];
    const transBody = reportData.transactions.map(t => {
        const phtDate = new Date(new Date(t.created_at + ' UTC').getTime() + (8 * 60 * 60 * 1000));
        return [
            t.transaction_number,
            phtDate.toLocaleDateString(),
            phtDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            t.customer_name || 'Walk-in',
            t.cashier_name || 'System',
            `PHP ${t.total_amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
        ];
    });

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('TRANSACTION DETAILS', 15, summaryY);

    autoTable(doc, {
        startY: summaryY + 5,
        head: transHead,
        body: transBody,
        theme: 'striped',
        headStyles: { fillColor: [51, 65, 85], textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 9, cellPadding: 3 },
        margin: { top: contentStartY + 5, bottom: 25 }
    });

    // --- Add Header and Footer to all pages ---
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        
        // Header
        let currentY = 15;
        if (shopLogo) {
            try {
                doc.addImage(shopLogo, 'PNG', 105 - 10, currentY, 20, 20);
                currentY += 25;
            } catch (err) {}
        }
        
        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.text(shopName.toUpperCase(), 105, currentY, { align: 'center' });
        currentY += 10;

        doc.setFontSize(14);
        doc.text(reportTitle, 105, currentY, { align: 'center' });
        currentY += 6;

        if (periodStr) {
            doc.setFontSize(10);
            doc.setFont('helvetica', 'bold');
            doc.text(periodStr, 105, currentY, { align: 'center' });
            currentY += 5;
        }
        
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.text(`Generated on: ${reportDate}`, 105, currentY, { align: 'center' });
        
        doc.setDrawColor(200, 200, 200);
        doc.line(15, currentY + 3, 195, currentY + 3);

        // Footer
        doc.setFontSize(10);
        doc.text(`Page ${i} of ${totalPages}`, 105, 287, { align: 'center' });
    }

    const pdfBase64 = doc.output('datauristring').split(',')[1];
    return {
        filename: `Report_${period}_${new Date().toISOString().split('T')[0]}.pdf`,
        base64Data: pdfBase64
    };
};
